"""
Django settings for wrapping project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os

from decouple import Config, RepositoryEnv
from decouple import config as decouple_config

import wrapping.settings.base as base

BASE_DIR = base.BASE_DIR
MEDIA_URL = base.MEDIA_URL
MEDIA_ROOT = base.MEDIA_ROOT
INSTALLED_APPS = base.INSTALLED_APPS
SITE_ID = base.SITE_ID
MIDDLEWARE = base.MIDDLEWARE
ROOT_URLCONF = base.ROOT_URLCONF
TEMPLATES = base.TEMPLATES
EMAIL_BACKEND = base.EMAIL_BACKEND
EMAIL_HOST = base.EMAIL_HOST
EMAIL_PORT = base.EMAIL_PORT
EMAIL_USE_TLS = base.EMAIL_USE_TLS
LOGIN_REDIRECT_URL = base.LOGIN_REDIRECT_URL
LOGOUT_REDIRECT_URL = base.LOGOUT_REDIRECT_URL
WSGI_APPLICATION = base.WSGI_APPLICATION
AUTH_USER_MODEL = base.AUTH_USER_MODEL
AUTH_PASSWORD_VALIDATORS = base.AUTH_PASSWORD_VALIDATORS
LANGUAGE_CODE = base.LANGUAGE_CODE
TIME_ZONE = base.TIME_ZONE
USE_I18N = base.USE_I18N
USE_TZ = base.USE_TZ
STATIC_URL = base.STATIC_URL
STATIC_ROOT = base.STATIC_ROOT
DEFAULT_AUTO_FIELD = base.DEFAULT_AUTO_FIELD


env_file = ".env.prod"
if os.path.exists(env_file):
    config = Config(RepositoryEnv(env_file))
else:
    # Fallback to standard config that reads from environment variables
    config = decouple_config

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY", default="default-development-secret-key")

# Load Supabase configuration from environment variables
SUPABASE_URL = config("SUPABASE_URL", default="https://default.supabase.co")
SERVICE_ROLE_KEY = config("SERVICE_ROLE_KEY", default="default-service-role-key")
SUPABASE_TUTORIAL_BUCKET = config(
    "SUPABASE_TUTORIAL_BUCKET", default="default-bucket-name"
)

EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="")

# This setting is important because the app is behind a reverse proxy
# that handles HTTPS connections and forwards the requests to Django.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# This setting forces all HTTP connections to be redirected to HTTPS.
SECURE_SSL_REDIRECT = True

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
ALLOWED_HOSTS = config("DJANGO_ALLOWED_HOSTS", default="").split(",")

# Necessary to enable CSRF tokens in production
CSRF_TRUSTED_ORIGINS = config("CSRF_TRUSTED_ORIGINS", default="").split(",")

# Adds a unique hash at the end of static files names when running collectstatic
# It ensures that old static files aren't cached and get reloaded when they change
STORAGES = {
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.ManifestStaticFilesStorage",
    },
}

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": config("DB_NAME", default="default_db_name"),
        "USER": config("DB_USER", default="default_user"),
        "PASSWORD": config("DB_PASSWORD", default="default_password"),
        "HOST": config("DB_HOST", default="localhost"),
        "PORT": config("DB_PORT", default="5432"),
    }
}
