# ruff: noqa: F401

"""
Django settings for wrapping project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os

from decouple import Config, RepositoryEnv
from decouple import config as decouple_config

from .base import (
    AUTH_PASSWORD_VALIDATORS,
    AUTH_USER_MODEL,
    BASE_DIR,
    DEFAULT_AUTO_FIELD,
    EMAIL_BACKEND,
    EMAIL_HOST,
    EMAIL_PORT,
    EMAIL_USE_TLS,
    INSTALLED_APPS,
    LANGUAGE_CODE,
    LOGIN_REDIRECT_URL,
    LOGOUT_REDIRECT_URL,
    MEDIA_ROOT,
    MEDIA_URL,
    MIDDLEWARE,
    ROOT_URLCONF,
    STATIC_ROOT,
    STATIC_URL,
    TEMPLATES,
    TIME_ZONE,
    USE_I18N,
    USE_TZ,
    WSGI_APPLICATION,
)

env_file = ".env.dev"
if os.path.exists(env_file):
    config = Config(RepositoryEnv(env_file))
else:
    # Fallback to standard config that reads from environment variables
    config = decouple_config

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY", default="default-development-secret-key")

# Load Supabase configuration from environment variables
# TODO MIGRATE TO DIFFERENT PROJECT
SUPABASE_URL = config("SUPABASE_URL", default="https://default.supabase.co")
SERVICE_ROLE_KEY = config("SERVICE_ROLE_KEY", default="default-service-role-key")
SUPABASE_TUTORIAL_BUCKET = config(
    "SUPABASE_TUTORIAL_BUCKET", default="default-bucket-name"
)

EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="")


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = ["*"]

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.path.join(BASE_DIR, "test_db.sqlite3"),
    }
}
