# Generated by Django 5.0.6 on 2024-07-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wrappinggallery", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="carry",
            name="title",
            field=models.CharField(default="TITLE", max_length=64),
        ),
    ]
