# Generated by Django 5.0.8 on 2024-09-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wrappinggallery", "0002_achievement_userachievement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="achievement",
            name="name",
            field=models.CharField(
                max_length=64, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
