# Generated by Django 5.0.6 on 2024-07-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wrappinggallery", "0002_carry_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carry",
            name="videoauthor",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
