# Generated by Django 5.0.6 on 2024-07-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wrappinggallery", "0003_alter_carry_videoauthor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carry",
            name="title",
            field=models.CharField(max_length=64),
        ),
    ]
