# Generated by Django 5.0.8 on 2024-09-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrappinggallery', '0003_alter_achievement_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, 'Wrapping'), (2, 'Contributor'), (3, 'Special')], null=True),
        ),
    ]
