# Generated by Django 5.0.8 on 2024-09-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrappinggallery', '0004_achievement_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='category',
            field=models.IntegerField(choices=[(1, 'Wrapping'), (2, 'Contributor'), (3, 'Special')]),
        ),
    ]
