# Generated by Django 5.0.8 on 2024-09-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wrappinggallery", "0006_alter_achievement_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievement",
            name="order",
            field=models.FloatField(blank=True, default=0.0),
            preserve_default=False,
        ),
    ]
