# Generated by Django 5.0.6 on 2024-07-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wrappinggallery", "0008_alter_ratings_votes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carry",
            name="pretied",
            field=models.BooleanField(null=True),
        ),
    ]
