# Generated by Django 5.0.9 on 2024-10-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wrappinggallery", "0008_alter_customuser_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="carry",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
