# Generated by Django 5.0.7 on 2024-07-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrappinggallery', '0009_alter_carry_pretied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carry',
            name='coverpicture',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
