# Generated by Django 5.2 on 2025-04-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wrappinggallery", "0011_alter_carry_finish"),
    ]

    operations = [
        migrations.AddField(
            model_name="carry",
            name="tutorial",
            field=models.BooleanField(default=False),
        ),
    ]
