# Generated by Django 5.0.7 on 2024-07-24 15:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wrappinggallery", "0012_alter_ratings_bigkids_alter_ratings_carry_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="userratings",
            constraint=models.UniqueConstraint(
                fields=("user", "carry"), name="unique_foreign_keys"
            ),
        ),
    ]
