# Generated by Django 5.2 on 2025-04-19 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrappinggallery', '0012_carry_tutorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carry',
            name='carrycreator',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='carry',
            name='tutorialmodel',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
