# Generated by Django 5.2 on 2025-07-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrappinggallery', '0013_carry_carrycreator_carry_tutorialmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='carry',
            name='carrycreator',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='carry',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='carry',
            name='tutorialmodel',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='carry',
            name='videoauthor',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='carry',
            name='videoauthor2',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='carry',
            name='videoauthor3',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='carry',
            name='videotutorial',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='carry',
            name='videotutorial2',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='carry',
            name='videotutorial3',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rating',
            name='votes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
