# Generated by Django 5.0.7 on 2024-08-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrappinggallery', '0014_alter_carry_mmposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carry',
            name='finish',
            field=models.CharField(choices=[('knotless', 'Knotless'), ('knotless tibetan', 'Knotless Tibetan'), ('tibetan', 'Tibetan'), ('TUB', 'Tied under bum'), ('TIF', 'Tied in front'), ('TAS', 'Tied at shoulder'), ('buleria', 'Buleria'), ('CCCB', 'Candy Cane Chest Belt'), ('slipknot', 'Slipknot'), ('ring(s)', 'Rings'), ('rapunzel', 'Rapunzel'), ('tied at the back', 'Tied at the back')], max_length=16),
        ),
    ]
