# Generated by Django 5.0.7 on 2024-08-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrappinggallery', '0015_alter_carry_finish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carry',
            name='mmposition',
            field=models.IntegerField(choices=[(-1, 'NA'), (0, 'Starts centred'), (0.5, 'Starts 0.5 measures off centre'), (1, 'Starts 1 measure off centre'), (1.5, 'Starts 1.5 measures off centre'), (2, 'Starts 2 measures off centre')]),
        ),
    ]
