# Generated by Django 5.0.7 on 2024-08-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrappinggallery', '0016_alter_carry_mmposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carry',
            name='shoulders',
            field=models.IntegerField(choices=[(0, 'Zero'), (1, 'One'), (2, 'Two')]),
        ),
    ]
