# Generated by Django 5.0.7 on 2024-08-02 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wrappinggallery', '0018_alter_carry_shoulders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carry',
            name='coverpicture',
        ),
    ]
