# Generated by Django 5.0.7 on 2024-08-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrappinggallery', '0020_alter_carry_finish'),
    ]

    operations = [
        migrations.AddField(
            model_name='carry',
            name='videoauthor2',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='carry',
            name='videoauthor3',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='carry',
            name='videotutorial2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carry',
            name='videotutorial3',
            field=models.URLField(blank=True, null=True),
        ),
    ]
