# Generated by Django 5.0.7 on 2024-08-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrappinggallery', '0021_carry_videoauthor2_carry_videoauthor3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carry',
            name='mmposition',
            field=models.IntegerField(choices=[(-1, 'NA'), (0, 'Starts centred'), (0.5, 'Starts 0.5 measures off centre'), (1, 'Starts 1 measure off centre'), (1.5, 'Starts 1.5 measures off centre'), (2, 'Starts 2 measures off centre'), (3, 'Starts centred on your chest'), (4, 'Starts centred on your back'), (5, 'Starts on your shoulder')]),
        ),
    ]
