# Generated by Django 5.0.7 on 2024-08-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrappinggallery', '0025_alter_carry_mmposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='carry',
            name='rings',
            field=models.BooleanField(default=False),
        ),
    ]
