# Generated by Django 5.0.8 on 2024-08-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrappinggallery', '0026_carry_rings'),
    ]

    operations = [
        migrations.AddField(
            model_name='carry',
            name='longtitle',
            field=models.CharField(default='longtitle', max_length=128),
            preserve_default=False,
        ),
    ]
