# Generated by Django 5.0.8 on 2024-08-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrappinggallery', '0028_carry_pass_cross_carry_pass_horizontal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carry',
            name='other_bunchedpasses',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='carry',
            name='other_chestpass',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='carry',
            name='other_eyelet',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='carry',
            name='other_legpasses',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='carry',
            name='other_s2s',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='carry',
            name='other_shoulderflip',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='carry',
            name='other_twistedpass',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='carry',
            name='other_waistband',
            field=models.BooleanField(default=0),
        ),
    ]
