# Generated by Django 5.0.8 on 2024-08-30 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrappinggallery', '0029_carry_other_bunchedpasses_carry_other_chestpass_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carry',
            name='layers',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')]),
        ),
        migrations.AlterField(
            model_name='carry',
            name='shoulders',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2')]),
        ),
    ]
