# Generated by Django 5.0.8 on 2024-09-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrappinggallery', '0030_alter_carry_layers_alter_carry_shoulders'),
    ]

    operations = [
        migrations.AddField(
            model_name='carry',
            name='other_poppins',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='carry',
            name='other_sternum',
            field=models.BooleanField(default=0),
        ),
    ]
