# Generated by Django 5.0.8 on 2024-09-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrappinggallery', '0031_carry_other_poppins_carry_other_sternum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carry',
            name='position',
            field=models.CharField(choices=[('front', 'Front'), ('back', 'Back'), ('tandem', 'Tandem')], max_length=10),
        ),
    ]
