# Generated by Django 5.0.8 on 2024-09-19 09:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrappinggallery', '0033_alter_carry_layers_alter_userratings_bigkids_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='leaners',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='legstraighteners',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='userratings',
            name='bigkids',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='userratings',
            name='difficulty',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='userratings',
            name='fancy',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='userratings',
            name='feeding',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='userratings',
            name='newborns',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='userratings',
            name='quickups',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
