# Generated by Django 5.0.8 on 2024-09-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrappinggallery', '0034_alter_ratings_leaners_alter_ratings_legstraighteners_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carry',
            name='layers',
            field=models.IntegerField(choices=[(-1, 'Varies'), (1, '1'), (2, '2'), (3, '3'), (4, '4')]),
        ),
        migrations.AlterField(
            model_name='carry',
            name='shoulders',
            field=models.IntegerField(choices=[(-1, 'Varies'), (0, '0'), (1, '1'), (2, '2')]),
        ),
    ]
