# Generated by Django 5.0.8 on 2024-09-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrappinggallery', '0035_alter_carry_layers_alter_carry_shoulders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carry',
            name='shoulders',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2')]),
        ),
    ]
