# Generated by Django 5.0.8 on 2024-09-19 17:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrappinggallery', '0036_alter_carry_shoulders'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='pregnancy',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='userratings',
            name='pregnancy',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
